"use client"

import { ChakraProvider } from '@chakra-ui/react'
import { Inter } from "next/font/google";
import Navbar from './(components)/Navbar';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Dev-Insight",
//   description: "Generated by team Lemon",
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrapper1'>
          <ChakraProvider>
            <div>
              <Navbar/>
            </div>
            {children}
          </ChakraProvider>
        </div>
      </body>
    </html>
  );
}
